apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: reports
type: Opaque
data:
  # These would be base64 encoded values in a real deployment
  username: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  password: eW91ci1hcHAtcGFzc3dvcmQ=      # your-app-password