apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30000
      name: api
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30001
      name: console
  type: NodePort