apiVersion: v1
kind: Namespace
metadata:
  name: datalakehouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: etl
---
apiVersion: v1
kind: Namespace
metadata:
  name: reports